### ISSUE TITLE
00011 - 数据增强

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-com#11]
Hi 炬康，
增强方式：
- 亮度补偿（明 暗）
- 竖直翻转

先做这个2块的增强，2个思路：
- 在训练代码外部完成；
- 与源代码（水平翻转）类似，增加以上2种方式增强；

**Comment by jaykky01** [comment]
Hi，孙工：
收到
亮度补偿暂时是明暗各一个我自己设定的值吗？

**Comment by FirminSun** [comment]
Hi 炬康；
一般是设定 范围 （0.8 - 1.2）. 假设原图是1， 变成0.8或1.2就会改变图像的亮度.

**Comment by jaykky01** [comment]
Hi，孙工：
收到！

**Comment by FirminSun** [comment]
Hi 炬康；
添加一个功能：将增强后的数据保存出来，方便调试查看.

**Comment by jaykky01** [comment]
Hi，孙工：
已完成两个数据增强方式和保存增强后数据功能的代码编写工作，主要思路以下：
首先roidb数据在一定程度上分成两个主要意义：什么图片上什么位置是什么东西；什么图片需要做什么操作；所以只要对某某图片的roidb数据进行增加某某操作的标签，同时在构造blob数据时检查是否需要对其进行相对应的操作即可。

从你发我的项目中，得到的方案是，只需要在roidb数据构造和blob数据构造操作中对部分数据增强操作参数进行检测和赋值，并添加对应的图片数据操作函数即可，无需对pascal_voc文件构造的roidb数据添加标签，方便以后增加其他数据增强操作和代码可读性。

实际操作如下
竖直翻转  主要思路为参考水平翻转，对整组roidb数据进行复制，并增加对应竖直翻转操作的参数--ver_flipped为True，同时其他操作不加以变化，单纯加以检测和保存；同时在minibatch.py中检测竖直翻转参数值，并加以翻转读取的图像数据；其中水平翻转参数use_hor_flipped和竖直翻转use_ver_flipped均加入至config.py中；
图像操作代码为   if 'ver_flipped' in roidb[i] and roidb[i]['ver_flipped']:    im = im[::-1, :, :]

亮度调整  主要思路为 新增config参数bright_adjuest=[0.8,1.2] 对输入的roidb进行整组复制两次，并设置其bright_scala，分别为0.8和1.2，按照上面的思路，进行构造roidb，并在构造blob中加以根据bright_scala参数对图像亮度进行调整。
图像操作核心代码为：
from skimage import exposure
im = exposure.adjust_gamma(im, gamma)  （gamma为bright_scala参数值）

综上，水平翻转、竖直翻转操作均会使得输入数据集乘以两倍，亮度调整会根据输入的roidb数据乘以bright_adjuest中值的个数+1的倍数（不包括1和小于0的数）；若三个操作都进行，则数据增强后的roidb数据将是原本的12倍；

同时加上了保存增强后的全部roidb数据，程序将会先检测是否存在增强后的roidb，若有将直接进行加载，免去前面的操作，若无则开展数据加载和增强操作，完成后保存增强后的全部roidb数据。

**Comment by jaykky01** [comment]
Hi，孙工：
已完成随机裁剪功能。
主要思路为 
1，通过resize将原图等比例缩放到高为1000，通过计算原图的高与预设的高1000之间的比例，进行缩放；
2.利用resize后的图像进行左上、右上、左下、右下、中点的五个位置裁剪图像，
3.根据裁剪位置，修正xml文件中的物体框；

其中文件中含有裁剪最靠近物体框的函数，供今后进行调用

**Comment by jaykky01** [comment]
Hi，孙工：
已完成图像旋转、平移操作的数据增强功能。
目前图像旋转已增加至程序中，水平移动还未，是否需要增加至程序中。

**Comment by FirminSun** [comment]
Hi 炬康;
移动也需要的添加：x 方向 和 y 方向都需要。

**Comment by jaykky01** [comment]
Hi，孙工：
已完成水平移动的数据增强工作，并嵌套至frcnn模型的数据准备工作中；
主要思路是：
1.通过shift_adjuest进行判断是否执行水平移动方式的数据增强；
2.若是，则通过设置shift_adjuest_x,shift_adjuest_y两个参数作为平移方向，其中x方向为正，代表向右平移，为负则向左平移；y方向为正，代表向下平移，为负则向上平移；
3.调整boxes物体识别框。根据平移方向重新调整平移框，若不在范围则移除，若全部boxes都不在范围，则不增加到roidb数据中；

**Comment by jaykky01** [comment]
Hi，孙工：
对于膨胀和缩小的操作，我目前的想法是：
对于膨胀和缩放的操作，其实在这里就是拉伸和缩放操作（我个人理解）；
1.主要是沿x/y方向进行拉伸延展和缩放；
2.通过factory_x,factory_y控制，大于1 则拉伸，小于1则缩放，等于1不做操作；
3.没有pad填0或255，拉伸后的长度是多少就是多少；
效果图如下：
![image](https://user-images.githubusercontent.com/40970231/44068706-0ce219b0-9fae-11e8-8d61-c105db7e6981.png)
拉伸前
![image](https://user-images.githubusercontent.com/40970231/44068719-2092728e-9fae-11e8-9e30-215b293a994a.png)
拉伸后

@FirminSun ，孙工，你觉得这样是否合理？

**Comment by FirminSun** [comment]
Hi  炬康；
可以，默认拉伸/缩放尺度稍微小些，0.1左右就可以。

**Comment by FirminSun** [comment]
Hi 炬康；
可以把每一个增强的效果一一放到这里来，以供参考。

**Comment by jaykky01** [comment]
Hi，孙工：
目前的数据增强操作共7种方式，效果分别如下：
原图效果
![image](https://user-images.githubusercontent.com/40970231/44139539-ef221c8e-a0a9-11e8-9a73-2a8b257c464e.png)
1.水平翻转
![image](https://user-images.githubusercontent.com/40970231/44139579-099c3fae-a0aa-11e8-8b36-d2facb124ba0.png)
2.竖直翻转
![image](https://user-images.githubusercontent.com/40970231/44139621-2d9af0d0-a0aa-11e8-9828-b405fa5e31d9.png)
3.随机裁剪5个位置，左上，左下，右上、右下、中间
![image](https://user-images.githubusercontent.com/40970231/44139792-b5c9fa78-a0aa-11e8-9eb0-19723f5cfeba.png)
4.旋转，旋转90度
![image](https://user-images.githubusercontent.com/40970231/44139847-e3d2041a-a0aa-11e8-8229-b7db2213a038.png)
5.调整亮度，调亮
![image](https://user-images.githubusercontent.com/40970231/44139904-1298a10a-a0ab-11e8-9fb9-011e2f5d0d46.png)
6.平移
![image](https://user-images.githubusercontent.com/40970231/44140223-04ee2f10-a0ac-11e8-9a00-61d7de400337.png)
7.膨胀
![image](https://user-images.githubusercontent.com/40970231/44140286-31963508-a0ac-11e8-958f-b204c5b1c25c.png)

**Comment by FirminSun** [comment]
Hi 炬康；
Wow,  You're Incredible.
A big task you done it. 
I must ask boss to give you a raise.
