### ISSUE TITLE
00014 - 修正Annotation中的图片尺寸信息

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-com#14]
Hi 炬康；
Annotation中，图片的width和height信息有可能不正确，写一个脚步，修复这个问题：
参考之前的data_precessing目录下的文件，应该有过类似的功能。

**Comment by jaykky01** [comment]
Hi，孙工：
已完成修正Annotations中xml的图像尺寸标签的对比功能。
主要思路为，通过读取xml文件信息，找到对应的图像路径并读取其图像尺寸，用xml文件尺寸标签数值与实际图像数值比较，若不一致则修改并存放于Annotation-new文件夹中。
另外还将不一致的尺寸信息写入log.txt文件中，以便检查。

**Comment by FirminSun** [comment]
Hi 炬康;
log.txt 非常好的idea.  同类的问题，也可以采用这个idea. 作为中间输出.

修正一下：
将Annotation-new 换成Annotations-old.  更新后的xml 文件保存于Annotations文件夹下.

**Comment by jaykky01** [comment]
Hi，孙工：
已添加代码修改成
将Annotation-new 换成Annotations-old. 更新后的xml 文件保存于Annotations文件夹下.
