### ISSUE TITLE
00015 - 自动检测cache中间数据

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-com#15]
Hi，孙工：
按照你的要求和指示，增加对cache进行自动检测功能；
若设置发生改变，则cache数据将自行进行重构并更替；
若设置不变，则cache数据将直接自动读取；

**Comment by jaykky01** [comment]
Hi，孙工：
已完成此部分代码编写，主要思路为将roidb数据改写成由数据包+数据操作合成的唯一id名，方便未来更多的数据包的存放。
合成方式：
1.数据包在前头，若多个，则data1+data2....；
2.数据增强码，目前固定顺序为：水平翻转、竖直翻转、调整亮度、旋转四个操作，若进行操作则为1，否则为0，构成8位数据，如11010000，后面4为暂时补0
fusion_2018-08-06_voc_2007_trainval_enhance_roidb_11010000.pkl代表是由fusion_2018-08-06数据包进行水平翻转、竖直翻转、旋转角度三个操作构成的roidb数据。

**Comment by FirminSun** [comment]
Hi 炬康;
文件夹可能需要检查是否存在，修复一下defect，详细查看附图：
![image](https://user-images.githubusercontent.com/16684985/43874501-c442297c-9bbe-11e8-8ff1-4ac862e303ab.png)

**Comment by jaykky01** [comment]
Hi,孙工：
此处已修复，代码中本身有检查路径是否存在，不存在则创建，但顺序反了，所以出现报错。目前修改完成

**Comment by FirminSun** [comment]
Hi  炬康；
Nice work.
Close it if done.
