### ISSUE TITLE
00016 - 提供可加载多VOC 数据包功能进行训练

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-com#16]
Hi，孙工：
按照你的要求和指示，增加一个功能：模型代码能够根据输入的参数进行加载多数据文件进行训练

**Comment by jaykky01** [comment]
Hi，孙工：
已完成此功能。
主要思路是通过trainval_net.py设定参与训练的数据包，并加载数据文件时构建image_index与文件所在路径的映射关系file_dict并储存在xx+xx_file_dict.log中，在加载文件时，根据相应的路径关系完成读取相应的文件即可。

**Comment by FirminSun** [comment]
Good!
