### ISSUE TITLE
00018 - 提供一个脚本，随机划分数据集

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-com#18]
Hi 炬康;
提供一个功能：将训练数据集划分为n等份, 随机划分：
比如：
all_train_data_resize2
==>
all_train_data_resize2_sub1, all_train_data_resize2_sub2, all_train_data_resize2_sub3 ...

**Comment by jaykky01** [comment]
Hi，孙工：
已完成此功能；
程序将根据输入的参数split_num，将目标文件夹等比例（最后一个文件夹数据量可能多点或少点），并存放于同路径下的xxx_sub1.2.3...文件下

**Comment by FirminSun** [comment]
Hi 炬康;
明确一点，最后一个文件夹，只能是少于或等于平均量.
分割完成后，为每一个文件夹产生 ImageSet.( txt 文件).

**Comment by jaykky01** [comment]
Hi,孙工：
此部分代码修改主要解决完善固定划分到最后的数据集 为小于或等于其他数据集 
核心思路是通过向上取整的方法计算每个文件夹所需要放置的文件，
同时通过其他py文件提供的函数在相应数据集下生成相应的txt文件
