### ISSUE TITLE
00019 - 添加用户训练setting.cfg, 覆盖默认值，避免多用户配置问题

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-com#19]
Hi 炬康;
添加用户训练setting.cfg,  覆盖默认值，避免多用户配置问题.
主要配置为：训练时用到的参数. 其他参数暂不考虑.

**Comment by jaykky01** [comment]
Hi，孙工：
已完成添加用户训练setting.cfg
主要思路为通过yaml来加载./data/cfgs/setting.cfg文件中的参数key和value，并覆盖默认值。

**Comment by jaykky01** [comment]
Hi，孙工：
已按照你的要求，完成文件存放位置变更代码修改。

**Comment by FirminSun** [comment]
Hi all,
个人的配置切勿上传！
