### ISSUE TITLE
00020 - 删除不再使用的代码相关部分代码

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-com#20]
Hi，孙工：
由于factory、pascal_voc.py代码中diff指向的是xml文件中difficult标签为1的object，但目前我们的代码中没有这部分标签的图像，故删除该部分代码，无需执行这块操作。

**Comment by jaykky01** [comment]
Hi，孙工：
目前已完成该部分代码的删除工作，并已上传至github，请查收

**Comment by FirminSun** [comment]
Hi 炬康；
关于Matlab中的代码，也删除掉。

**Comment by jaykky01** [comment]
Hi，孙工：
关于matlab部分的，主要两块：
1.config.py中的__C.matlab;
2.reval.py，这个文件主要用于matlab的测试评估，且未用到，故删除

**Comment by FirminSun** [comment]
Hi  all;
如遇到其他不再使用的代码，亦可将其删除。
