### ISSUE TITLE
00024 - 整理代码，不使用data_processing代码、新增数据增强代码文件以及整理morelib代码

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-com#24]
HI，孙工：
此issue主要用于标记代码的整理工作，主要工作包含：
1.不再使用data_processing代码；
2.删除过多的init_path，以免import错误；
3.整理morelib代码，抽出函数放置在util文件中
4.新增数据增强文件，放置数据增强的代码；

**Comment by jaykky01** [comment]
Hi,孙工：
已完成部分代码修改

**Comment by FirminSun** [comment]
Nice!
