### ISSUE TITLE
00025 - 修改roidb.py，避免重复读取图像尺寸，加快数据准备工作速度

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-com#25]
Hi，孙工：
roidb.py的作用主要在于对原始的roidb数据进行扩充，更好的对图像建立标签属性，其中需要添加图像的尺寸，若按原始的思路，是需要打开全部的roidb数据对应图像，读取其尺寸；但随着数据增强操作越来越多，roidb翻倍现象越来月频繁，此操作将会大大影响效率。同时读取roidb数据对应图像尺寸，其实在数据增强操作就有所体现。
因此，目前将读取roidb数据对应图像的尺寸的操作提前到在数据增强阶段进行。进而减少冗余操作，加快数据准备工作速度。

**Comment by FirminSun** [comment]
Hi 炬康；
Good idea. This makes our work more efficient.
Close issue if completed.
