### ISSUE TITLE
00026 - 检查背景图像长宽大小和图片错误情况

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-com#26]
HI，孙工：
根据你的指示，此issue是用于检查fusion_data/background.zip中的背景图片的一些问题：
1.长宽大小是否过小。统计图像的长宽最小值，筛选出阈值以下的图像，初定为最短边为800
2.检查是否存在图像错误情况，是否为空，是否无法打开等异常。

**Comment by FirminSun** [comment]
Hi 炬康;
最短边确定为选择800， 不符合的全部删除;
异常数据直接删除;
删除之后，重新上传FTP;
压缩包名为：background_min_800.zip.

**Comment by FirminSun** [comment]
Hi 炬康；
此处的理解：
600：表示最短边大于等于 600，切记，不是最短边设置为600.
1000：表示最长边小瑜等于 1000

**Comment by FirminSun** [comment]
Hi 炬康；
此问题是否已经完成？
Close it if done

**Comment by jaykky01** [comment]
Hi，孙工：
此问题已完成。
