### ISSUE TITLE
00027 - 序列化args，保存到本地

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-com#27]
Hi 炬康;
- 任务需求：
将args参数序列化，保存到本地。
需要重新改写args的代码，目前已经完成一部分。

- 关键点：
保存路径：根据之前的args.tag基本原理，将参数保存到对应文件夹下，以供后期模型调参。

- 参考：
tools/serialize_argparse.py
tools/serialize_argparse_test.py

**Comment by jaykky01** [comment]
Hi,孙工：
目前需求是需要在加载args参数后，进行序列化保存到本地对应文件中，我能想到 序列化保存到本地的作用仅仅是用作保存参数，供之后查看。所以想问还有别的目标吗？
我的想法是，可以拓展他的用途，在args_training.cfg中加入一个判断加载args.json文件的标志，若True则，加载指定路径下的args.json并放弃加载args_training.cfg的其余参数，否则不加载并将参数序列化。

 你觉得这样的思路是否能够达到需求？
@FirminSun

**Comment by FirminSun** [comment]
Hi 炬康；
此Idea很好，可尽可能多的拓展其功能，发挥最大作用。
默认值暂时取false。

**Comment by jaykky01** [comment]
Hi，孙工：
已完成此部分代码编写。主要思路如上。同时将serialize_argparse.py移至morelib.utils下，serialize_argparse_test移至morelib.bin下

**Comment by FirminSun** [comment]
Hi  炬康；
关于参数加载的逻辑同步更新的ReadMe文件上。

**Comment by FirminSun** [comment]
Hi 炬康；
args参数添加：
- GPU选择（--gpu），默认为0
- 预加载权重， 即指定fine-tuning 权重 （--snapshot），优先选择指定权重，否则选择默认。

另外，思考一下，是否还有需要添加的？

**Comment by jaykky01** [comment]
Hi，孙工：
  对于预加载权重的参数，可以是由两个参数来控制：
  1.是否进行预加载权重
  2.若是，预加载权重的路径；
 
 另外还需添加的话，我觉得可以是将classes.txt的文件名作为参数，因为目前若需要修改读取classes.txt是需要打开pascal_voc.py文件中进行修改，若放置在参数中，可更加便捷

**Comment by jaykky01** [comment]
Hi，孙工：
  对于预加载权重的参数，可以是由两个参数来控制：
  1.是否进行预加载权重
  2.若是，预加载权重的路径；
 
 另外还需添加的话，我觉得可以是将classes.txt的文件名作为参数，因为目前若需要修改读取classes.txt是需要打开pascal_voc.py文件中进行修改，若放置在参数中，可更加便捷

**Comment by FirminSun** [comment]
Good!
