### ISSUE TITLE
00003 - 编译文件更替

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-com#3]
孙工，你好：
由于文件存在需要本机编译的so文件，分别是nms、lib文件夹下，所以我上传后，你pull下来后将会需要替换相关编译文件方可正常运行，请知悉！

**Comment by FirminSun** [comment]
Hi 炬康；
这个不需要上传，每个人的机器不一样， 他自己会完成这个编译任务。
只需要上传代码和相关文件就可以。
@jaykky01

**Comment by jaykky01** [comment]
好的，我看看如何选择只上传选中项
