### ISSUE TITLE
00004 - 添加标签存放文本（classes_label_name.json）

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-com#4]
Hi 炬康；

以下标签数据，用一个文本存放，通过读取文本获取此标签数据.

CLASSES = ('__background__',
           'aeroplane', 'bicycle', 'bird', 'boat',
           'bottle', 'bus', 'car', 'cat', 'chair',
           'cow', 'diningtable', 'dog', 'horse',
           'motorbike', 'person', 'pottedplant',
           'sheep', 'sofa', 'train', 'tvmonitor')

@jaykky01

**Comment by jaykky01** [comment]
Hi 孙工：
已完成标签的输出和读取，输出在于zjai_createData/zjai_4_getAllLabel.py会获取标签并以文本形式存放于./data/train_data/classes.txt文件中；而标签的读取在于pascal_voc.py文件的_get_classes()函数会自动读取该路径下的classes.txt文件得到tuple类型的classes

**Comment by FirminSun** [comment]
Good job! 
获取根目录尽量通过 config 配置统一获取。
涉及到环境配置，都需要考虑这个问题。
比如：文件存放，中间输出.

code：
root_dir = osp.abspath(osp.join(osp.dirname(__file__), '..'))
