### ISSUE TITLE
00005 - voc_classes.txt 添加

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-com#5]
Hi 炬康；
添加voc_classes.txt, 存放在data/cfgs/voc_classes.txt
参考data/cfgs/com_classes.txt

**Comment by jaykky01** [comment]
Hi，孙工；
voc_classes.txt是voc2007数据集的标签吗？另外想问下为什么需要加入cfg文件下，作用在于什么～

**Comment by FirminSun** [comment]
Hi，
是的， voc2007数据集的标签;
存放classes 标签的文件夹, 将来会有新标签进来，会根据不同数据集读取不同标签；
@jaykky01

**Comment by jaykky01** [comment]
哦哦，明白

**Comment by jaykky01** [comment]
Hi，孙工；
我在zjai_createData文件下有专门统计标签的py文件，这样的话，我只需要修改结果文件的存储路径就好了

**Comment by jaykky01** [comment]
Hi，孙工；
已完成添加voc_classes.txt至data/cfgs文件夹下工作。主要思路是基于原有代码，通过微调、合并等操作，更新zjai_4_get_all_label.py，统计Annotations文件夹下的xml文件中的object标签，完成统计后写入到data/cfgs路径下，通过修改set_name来修改classes文件名，"{}_classes.txt".format(set_name)

**Comment by jaykky01** [comment]
Hi,孙工；
补充：
voc_classes文件中的一行代表一个label；且bachground排在第一行

**Comment by FirminSun** [comment]
Hi 炬康；
good.
