### ISSUE TITLE
00006 - self._num_classes 动态赋值

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-com#6]
Hi 炬康；
file：imdb.py
![image](https://user-images.githubusercontent.com/16684985/42811772-34e31142-89ee-11e8-99aa-49ef82fa46fa.png)

self._num_classes = 170 修改这个参数值， 通过参数classes 获取_num_classes.

**Comment by jaykky01** [comment]
Hi，孙工：
已完成动态赋值工作，主要思路是通过self._classes的取len即可，但将self._num_classes=len(self._classes)语句防止self_classes的赋值语句之下

**Comment by FirminSun** [comment]
Hi 炬康；
未测试通过的代码，不能上传。 这样修改还不行：
file: pascal_voc.py

![Uploading image.png…]()

**Comment by jaykky01** [comment]
Hi，孙工：
明白。之后不会再犯。我再去研究测试代码和过程值

**Comment by FirminSun** [comment]
Good.
