### ISSUE TITLE
00007-函数在类里面和类之外的区别是什么？

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-com#7]
Hi，孙工：
我看到你更新代码中，将一个函数从pascal_voc类里面放置到类外面，想问下其之间的区别是什么？具体例子在pascal_voc.py的read_classes函数体现。

**Comment by FirminSun** [comment]
Hi 炬康,
pascal_voc.py 只是解析 pascal数据集， 还有其他数据集需要使用这个 read_classes函数，此函数将是所有数据集都使用， 昨天不是让你添加voc_classes.txt文件嘛。
coco数据集或者将来的数据集都会这样扩展，这就是考虑到将来程序的扩展性，功能上没什么区别。
