### ISSUE TITLE
00008 - 预测功能实现

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-com#8]
Hi 炬康；
预测功能实现：
函数传入一张图片： predict(image)
返回一个list:
类别标签，预测分，x1, y1, x2, y2
'glg-glgblzbg-hz-mcxcw-45g', 0.931, 1049, 570, 1492, 1103

代码类似如下：
        data = ["{},{:.3f},{},{},{},{}".format('glg-glgblzbg-hz-mcxcw-45g', 0.931, 1049, 570, 1492, 1103)]
        data.append("{},{:.3f},{},{},{},{}".format('bl-blht-dz-yw-6.7g',0.850,493,516,1121,1148))
        data.append("{},{:.3f},{},{},{},{}".format('bl-blht-dz-yw-6.7g',0.850,493,516,1121,1148))
        data.append("{},{:.3f},{},{},{},{}".format('wwsp-wwxxs-dz-yw-60g',0.838,660,253,1248,591))
        data.append("{},{:.3f},{},{},{},{}".format('wwsp-wwxxs-dz-yw-60g',0.838,660,253,1248,591))
        data.append("{},{:.3f},{},{},{},{}".format('wwsp-wwxxs-dz-yw-60g',0.838,660,253,1248,591))
        return data

**Comment by jaykky01** [comment]
Hi，孙工：
已完成预测功能，主要有predict.py和batch_predict.py两个文件实现，前者核心为单张图片识别函数(detect_single_image)，供后者调用，所需输入为会话sess,net,im,CLASSES，即可返回分数大于阈值的结果box_list,score_list,cls_list，若list长度不为一即代表图片有多个目标；而后者核心在于批量预测，通过传入所需要的参数进行加载网络架构和参数、读取图像等准备工作，并将结果写入对应名称的xml文件中；

**Comment by FirminSun** [comment]
Hi 炬康；
predict.py 单张预测结果返回按我上面提到的返回。
类别标签，预测分，x1, y1, x2, y2
'glg-glgblzbg-hz-mcxcw-45g', 0.931, 1049, 570, 1492, 1103 ==》 作为一条记录，表示一个目标
将结果放到一个 list 里面返回。

batch_predict.py 修改为 predict_batch.py

**Comment by jaykky01** [comment]
Hi，孙工:
好的，已经修改成放到一个list里面返回出来了。
名字也修改了~

**Comment by FirminSun** [comment]
Hi 炬康；
提示代码：
boxes = np.zeros((0, 5))
boxes = np.append(boxes, box, axis=0)
