### ISSUE TITLE
00009 - 设置STEPSIZE来调整学习率

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-com#9]
Hi，孙工；
通过阅读和理解代码，得到结论是：
1.通过调整STEPSIZE、GAMMA参数可以设置梯度性的学习率，如在某步数区间，learning rate*=GAMMA;
2.目前代码是支持多梯度的步数区间，只需设置STEPSIZE即可，无需修改代码，如设置STEPSIZE=[30000,50000,70000]，初始lr为0.001，那么0-30000iter时lr为0.001,30001-50000时lr为lr×GAMMA（注意此处将会更替lr值，即lr不再是0.001）；50001-70000时lr将会是lr×GAMMA；

**Comment by FirminSun** [comment]
Hi 炬康；
very nice.
